### ISSUE TITLE
Official handover?

### ISSUE THREAD

**Issue by mcdope** [aluzzardi/pam_usb#54]
Hey @aluzzardi,

This time it's not an accidential PR in the wrong repository but a legit question 😁 😆 ...

First of all: I LOVE pam_usb, which is also why I forked it to keep it alive for myself. Thank you so much for your work!

In https://github.com/aluzzardi/pam_usb/issues/36#issuecomment-326965157 you said you would be happy to hand over maintainership to committed persons. 

By now my fork is available for over four years and has introduced quite a bit of new features or enhancements of existing ones. I also have a plan to reach a v1, and to get pam_usb upstreamed (again). 

For Arch, it's even the "recommened" repo (based on [AUR](https://aur.archlinux.org/packages/pam_usb)). 

For Ubuntu (at least [for german users](https://wiki.ubuntuusers.de/Authentifizierung_mit_USB-Stick/)) it's also the recommened one - but that doesn't count because I wrote that Wiki article myself 🤣.

Guess we can agree on "I am committed", so... 

May I ask for your endorsement and may I submit a PR to put a link in the `README.md``? Or maybe you want to do the latter yourself? If you have any objections, please say so - I will try hard to solve them.

Highest regards, 
Tobias

**Comment by galliotxy** [comment]
您好，您的邮件已经收到。我会尽快查收的~

**Comment by aluzzardi** [comment]
@mcdope 💯 

Yes, I'd be happy to. Thanks for continuing the project!

**Comment by mcdope** [comment]
> @mcdope 💯
> 
> Yes, I'd be happy to. Thanks for continuing the project!

Thanks, just submitted a small PR adding a note about it in the README.
